---
Title: Yard Capture
date: 
---

```{r, "libraries",  echo=FALSE, message=FALSE }
## We select an accessible color pallate with black:
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
names(cbbPalette) <- c("black","orange","sky","green","yellow","blue","red","pink")


## https://stackoverflow.com/questions/4090169/elegant-way-to-check-for-missing-packages-and-install-them
r = getOption("repos") 
r["CRAN"] = "http://lib.stat.cmu.edu/R/CRAN/" 
options(repos = r)
rm(r)

using <- function(...) {
    libs<-unlist(list(...))
    req<-unlist(lapply(libs,require,character.only=TRUE))
    need<-libs[req==FALSE]
    if(length(need)>0){ 
        install.packages(need)
        lapply(need,require,character.only=TRUE)
    }
}

libs <- c("Hmisc","tidyverse","dplyr","clock","tigris","ClusterR","cluster","ggmap","ggplot2","rvest","showtext","sp","sf","tidycensus","tmap","icons","fontawesome")
using(libs)
```



```{r,}

## https://datacarpentry.org/r-raster-vector-geospatial/06-vector-open-shapefile-in-r/
tgwlist <- st_read("grasslist2.shp")
parcels <- st_read("ParcelBoundaries/ParcelBoundariesByMAPBLOLOT.shp")
parcels <- parcels %>% rename("Locatin"="ParcelAddr")
bmplist <- read.csv("ApplicantInformationDatabase.csv")
bmplist <- bmplist %>% rename("Locatin"="X..Parcel.Street.Address1..")
inaturalist <- read.csv("inaturalist-265817.csv")
inaturalist_sp <- st_as_sf(inaturalist, coords = c("longitude", "latitude"), crs = st_crs(tgwlist))
inaturalist_sp <- st_transform(inaturalist_sp, crs=st_crs(parcels))
tgwlist <- st_transform(tgwlist, crs=st_crs(parcels))

tgwi <- st_intersects(parcels,tgwlist)
parcelstgw <- parcels[lengths(tgwi)>0,] # for plotting 

##st_intersection(parcels,inaturalist_sp)
inat <- st_intersects(parcels,inaturalist_sp) 
parcelsinat <- parcels[lengths(inat)>0,] # to add Locatin 

sum(tolower(bmplist$Locatin) %in% tolower(parcelsinat$Locatin))
sum(tolower(tgwlist$Locatin) %in% tolower(parcelsinat$Locatin))
sum(tolower(tgwlist$Locatin) %in% tolower(bmplist$Locatin))
sum(tolower(tgwlist$Locatin) %in% tolower(bmplist$Locatin)&tolower(tgwlist$Locatin) %in% tolower(parcelsinat$Locatin))
```

```{r,}
ggplot() + 
  geom_sf(data = parcelstgw[tolower(tgwlist$Locatin) %in% tolower(parcelsinat$Locatin),], size = 3, color = "black", fill = "cyan1") + 
  ggtitle("Parcels") + 
  coord_sf()
```

```{r, 'main map setup', eval = TRUE, echo=FALSE, message=FALSE}
tmap_options(check.and.fix = TRUE)
tmap_mode("view")
tgwinat <- tm_shape(parcelstgw[tolower(parcelstgw$Locatin)%in%tolower(parcelsinat$Locatin),], name="inaturalist tgw lawns") +
  tm_fill(
    col = "Acres",
    palette = "-Greens",
    style = "cont",
    contrast = c(0.1, 1),
    title = "Inaturalist TGW violations",
    id = "summary_value", #"GEOID",
    popup.vars = c("Owner","SqFeet","Locatin"),
    showNA = FALSE,
    alpha = 0.8) +
    tm_borders(col = "darkgray", lwd = 0.7)
tgwbmp <- tm_shape(parcelstgw[tolower(parcelstgw$Locatin)%in%tolower(bmplist$Locatin),], name="bmp tgw lawns") +
  tm_fill(
    col = "Acres",
    palette = "-Greens",
    style = "cont",
    contrast = c(0.1, 1),
    title = "Bmp TGW violations",
    id = "summary_value", #"GEOID",
    popup.vars = c("Owner","SqFeet","Locatin"),
    showNA = FALSE,
    alpha = 0.8) +
    tm_borders(col = "darkgray", lwd = 0.7)
bmpinat <- tm_shape(parcelsinat[tolower(parcelsinat$Locatin)%in%tolower(bmplist$Locatin),], name="bmp inaturalist lawns") +
  tm_fill(
    col = "Acres",
    palette = "-Greens",
    style = "cont",
    contrast = c(0.1, 1),
    title = "Bmp Inaturalist lawns",
    id = "summary_value", #"GEOID",
    popup.vars = c("Owner","SqFeet","Locatin"),
    showNA = FALSE,
    alpha = 0.8) +
    tm_borders(col = "darkgray", lwd = 0.7)

bmpinattgw <- tm_shape(parcelsinat[tolower(parcelsinat$Locatin)%in%tolower(bmplist$Locatin)&tolower(parcelsinat$Locatin)%in%tolower(parcelstgw$Locatin),], name="bmp inaturalist tgw lawns") +
  tm_fill(
    col = "Acres",
    palette = "-Greens",
    style = "cont",
    contrast = c(0.1, 1),
    title = "Bmp Inaturalist tgw lawns",
    id = "summary_value", #"GEOID",
    popup.vars = c("Owner","SqFeet","Locatin"),
    showNA = FALSE,
    alpha = 0.8) +
    tm_borders(col = "darkgray", lwd = 0.7)

```
